### ISSUE TITLE
Convert to using Pathlib

### ISSUE THREAD

**Issue by AdrianDAlessandro** [omicsNLP/Auto-CORPus#39]
All of the path handling is done using strings and `os.path` this is prone to issues with running on different operating systems. Best practise for path-handling in Python is to use the inbuilt `pathlib` module.

**Comment by tsmbland** [comment]
I'll give this one a go

**Comment by tsmbland** [comment]
@AdrianDAlessandro @alexdewar @jmp111 PR created! https://github.com/omicsNLP/Auto-CORPus/pull/57
