### ISSUE TITLE
Change to abbreviation algorithm

### ISSUE THREAD

**Issue by jmp111** [omicsNLP/Auto-CORPus#9]
I noticed a change compared to a previous version of the algorithm:
https://github.com/omicsNLP/Auto-CORPus/blob/b5140ff8b7e4f6bc1ad101d25bdd9b0ed2ea9a30/src/abbreviation.py#L402
Above only new terms from full text are added to those found from an abbreviations section.
There is an exception for which this is not ideal: when the same abbreviation is used for different terms in the same text.
It will only keep the first one (likely the one in the abbreviation section).

@Tom-Shorter, can we change the output to a list and if the abbreviation section and full text algorithm are the same, then skip, but otherwise list both abbreviations. Test with PMC4068805 (where RP is defined in abbreviation section as reverse phase, but in the text as reversed phase (this one is correct actually)).

**Comment by jmp111** [comment]
Also, can we only output the all_abbreviations list going forward? We can add a tag to each item how it was found? Then the duplicates can be tagged both as abbreviation_section and fulltext_algorithm?

**Comment by Tom-Shorter** [comment]
This issue has been addressed in pull request #11. The abbreviations file format has been reworked and all full terms are now kept along with the extraction method(s) used to find the abbreviation
